#-----------------------------------------------------------------------------------------------------------------------
# Minimum Starting Point recipe
#
# Self contained Spinnaker installation with no external dependencies and no additional configuration needed.
# This is intended as a starting point for any kubernetes cluster.
# Not for production use.
#
# Features:
# - One Kubernetes account (Spinnaker's own cluster) for deployment targets
# - Spinnaker authentication disabled
# - Self hosted minio as a persistent storage
# - Self hosted redis backend for caching and temporal storage of services
#-----------------------------------------------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where spinnaker and all its infrastructure will be installed.
# NOTE: If changed, also change it in all ClusterRoleBinding namespace references.
namespace: spinnaker

resources:
  - spinnakerservice.yml             # (Mandatory). Base spinnaker manifest
  - infrastructure/minio.yml         # Self hosted minio, a S3 compatible data store
  - accounts/kubernetes/spin-sa.yml  # Kubernetes service account needed by patch-kube.yml

patchesStrategicMerge:
  - persistence/patch-minio.yml   # (Mandatory). Persistence to store spinnaker applications and pipelines
  - accounts/kubernetes/patch-kube.yml  # Kubernetes accounts
