#-----------------------------------------------------------------------------------------------------------------------
# Quick Start recipe
#
# Self contained Spinnaker installation with no external dependencies and no additional configuration needed.
# Not for production use.
#
# Features:
# - One Kubernetes account (Spinnaker's own cluster) for deployment targets
# - One dockerhub account for public repositories
# - Spinnaker authentication disabled
# - Spinnaker exposed out of the cluster using 2 public Kubernetes service load balancers
# - Self hosted minio as a persistent storage
# - Self hosted redis backend for caching and temporal storage of services
#-----------------------------------------------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where spinnaker and all its infrastructure will be installed.
# NOTE: If changed, also change it in all ClusterRoleBinding namespace references.
namespace: spinnaker

resources:
  - spinnakerservice.yml             # (Mandatory). Base spinnaker manifest
  - infrastructure/minio.yml         # Self hosted minio, a S3 compatible data store
  - infrastructure/redis.yml
  - accounts/kubernetes/spin-sa.yml  # Kubernetes service account needed by patch-kube.yml

patchesStrategicMerge:
  - persistence/patch-minio.yml   # (Mandatory). Persistence to store spinnaker applications and pipelines
  - persistence/patch-redis.yml
  - expose/patch-lb.yml                 # Automatically expose spinnaker
  - accounts/kubernetes/patch-kube.yml  # Kubernetes accounts
  - accounts/docker/patch-dockerhub.yml # Docker accounts
