#-----------------------------------------------------------------------------------------------------------------
# RBAC configuration for a kubernetes service account (see patch-kube.yml)
#-----------------------------------------------------------------------------------------------------------------
## NOT FOR PRODUCTION USE/CONFIG
## The use of 'cluster-admin' is for POC work only.
## For production config, consult Armory for proper privilege assignment. See spin-sa.yml for example.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spin-sa
  namespace: spinnaker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spin-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: spin-sa
    namespace: spinnaker
