#-----------------------------------------------------------------------------------------------------------------
# Example configuration for enabling terraformer stages in spinnaker
#
# Feature documentation: https://docs.armory.io/docs/armory-admin/secrets/secrets-vault/
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:  
    config:
      armory:
        secrets:
          vault:
            enabled: true
            authMethod: KUBERNETES                      # Method used to authenticate with the Vault endpoint. Must be either KUBERNETES for Kubernetes service account auth or TOKEN for Vault token auth. The TOKEN method will require a VAULT_TOKEN environment variable set for Operator and the services.  
            url: vault.myorg.com:443     # URL of the Vault endpoint from Spinnaker services.
            path: kubernetes-spinnaker                  # (Optional; default: kubernetes) Applies to KUBERNETES authentication method) Path of the kubernetes authentication backend mount. Default is "kubernetes"
            role: spin-sa                               # (Applies to KUBERNETES authentication method) Name of the role against which the login is being attempted.
