#-----------------------------------------------------------------------------------------------------------------
# Example configuration for adding a gitlab account to spinnaker
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      artifacts:
        gitlab:
          enabled: true
          accounts:
          - name: gitlab
            token: encrypted:k8s!n:spin-secrets!k:gitlab-token  # (Secret). Gitlab token.
#            tokenFile: encryptedFile:k8s!n:spin-secrets!k:gitlab-tokenfile # (Secret). File containing a gitlab authentication token.
