apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Namespace where spinnaker operator will be installed.
# NOTE: If changed, also change it in ClusterRoleBinding namespace references.
namespace: spinnaker-operator
resources:
  - deploy/operator/cluster/role.yaml
  - deploy/operator/cluster/service_account.yaml
  - deploy/operator/cluster/role_binding.yaml
  - deploy/operator/cluster/deployment.yaml
patchesStrategicMerge:
  - patch-config.yaml # Support for custom operator configuration. Depends on operator-config.
#  - patch-validations.yaml  # Disable all validations done by the operator globally. After disabling validations you would need to manually delete the webhook configuration previously created by operator: "kubectl delete validatingwebhookconfiguration spinnakervalidatingwebhook"

configMapGenerator:
  - name: operator-config
    files:
      - halyard-local.yml
generatorOptions:
  disableNameSuffixHash: true
  
# This section is used if you need to pull operator images from a different docker registry than the default, like when running in air-gapped environments
#images:
#  - name: armory/armory-operator
#    newName: mydocker.io/armory/armory-operator
#  - name: armory/halyard-armory
#    newName: mydocker.io/armory/halyard-armory
